### ISSUE TITLE
Your bot is malfunctioning

### ISSUE THREAD

**Issue by robsheldon** [suvakov/gitland-client#1]
I have enjoyed competing with you for the top spot in the gitland game. :-) But your bot appears to be stuck now and this is making the game less fun.

**Comment by suvakov** [comment]
Thanks. I thought that game is restarted (I checked few hours ago and my bot was not listed in players/ dir) and turn it off. It is back online now:)

**Comment by robsheldon** [comment]
Fantastic! Happy to have you back.
